version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8.1
      - image: circleci/mysql:latest
    environment:
      - NODE_ENV: development
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: npm-install
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run:
          name: test
          command: npm test
