version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8.1
      - image: circleci/mysql:latest
    environment:
      - NODE_ENV: development
    steps:
      - checkout
      - run:
          name: update-npm
          command: 'sudo npm install -g npm@5.6; sudo npm install are-we-there-yet'
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: npm-install
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run:
          name: test
          command: npm test
